### ISSUE TITLE
parseQuery not working with FunctionExpressions

### ISSUE THREAD

**Issue by gla5001** [paustint/soql-parser-js#130]
- [ ] Feature
- [X] Bug

## Description
Not necessarily a bug (i might be doing something wrong), but I recently upgraded to version `3.0.0` and now parseQuery does not work with any FieldFunctionExpression. Locally, if I try and example from the demo site, like 

```
import { parseQuery } from 'soql-parser-js';
const parsedQuery = parseQuery('SELECT CampaignId, AVG(Amount) avg FROM Opportunity GROUP BY CampaignId HAVING COUNT(Id, Name) > 1');
```

it throws an error 

```
TypeError: ctx.functionExpression.map(...).flat is not a function
```

**Comment by ABenassi87** [comment]
@paustint I can take a look if you want it

**Comment by paustint** [comment]
@gla5001 - This query is parsed correctly on the example website (https://paustint.github.io/soql-parser-js/), so it should work fine locally on the latest version.

I hadn't intentionally done this, but just realized that this library requires node version `11.0` or higher or a polyfill. And all browsers aside from IE should support . this as well.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

What environment are you working in and what version?

**Comment by gla5001** [comment]
ah. I bet thats it. My project is running node 10.14 (which i need to upgrade as well), so that sounds like it could be this issue. I'll try upgrading and trying again. Thanks for the info @paustint.

**Comment by gla5001** [comment]
Yup. That did the trick. Its working now.
