### ISSUE TITLE
isQueryValid doesn't properly validate SOQL syntax

### ISSUE THREAD

**Issue by pgonzaleznetwork** [paustint/soql-parser-js#152]
The isQueryValid function doesn't seem to actually validate that the query is valid per SOQL (as opposed to SQL) standards. I was able to easily reproduce this

```
let { isQueryValid } = require('soql-parser-js');

function test(connection,query){

    const validSoql = `SELECT Name INVALID FROM Account INVALID`;

    console.log(isQueryValid(validSoql));// << returns true even though the above would fail in sfdc
}
```

**Comment by paustint** [comment]
@pgonzaleznetwork - Thank you for reporting this bug! It does look like `Name INVALID` is reported as valid, even though the field alias is not supported in this case.

The object alias is valid, and I played around with it just to be sure - for example the following is valid:

```sql
SELECT INVALID.Name,
    FORMAT(CreatedDate) dte,
    FORMAT(CreatedDate),
    FORMAT(INVALID.CreatedDate) dte1
FROM Account INVALID
```

-----

Also, as I was reviewing the docs for aliases, I noticed another case that throws an error but it is actually a valid query: `SELECT count() FROM Contact c, c.Account a WHERE a.name = 'MyriadPubs'`

I don't know that it is worth all the hassle to support this specific case.


Documenting here just for my future reference:
>The following are SOQL keywords that can’t be used as alias names: AND, ASC, DESC, EXCLUDES, FIRST, FROM,
GROUP, HAVING, IN, INCLUDES, LAST, LIKE, LIMIT, NOT, NULL, NULLS, OR, SELECT, WHERE,
WITH

**Comment by pgonzaleznetwork** [comment]
Thanks!

**Comment by paustint** [comment]
@pgonzaleznetwork - After looking into this, it looks like the main issue is that all fields allow an alias when there is a `GROUP BY` clause present, which isn't known at the time that the fields are being parsed.

This change would require some gymnastics, and I am going to leave the current behavior as-is for now even though there is a bug.

**Comment by pgonzaleznetwork** [comment]
@paustint thanks for the update. Would you be able to provide some pointers as to where in the code this is happening and where the fix would be needed? I'd like to see if at least I can fix this in my own version since I would really benefit from this functionality. Thanks!

**Comment by pgonzaleznetwork** [comment]
@paustint  Ignore the above, I thought this reply was in relation to the other issue I reported a few days ago.
