### ISSUE TITLE
keep literalType in the result JSON

### ISSUE THREAD

**Issue by ghingis** [paustint/soql-parser-js#207]
- [ ] Feature
- [x] Bug

## Description
Is it possible to keep the literal type for the subqueries in the condition clause?

Currently a query like this:
`SELECT Id FROM Account WHERE Id IN (SELECT AccountId FROM Opportunity)`
returns with the following result:
```
{
  "fields": [
    {
      "type": "Field",
      "field": "Id"
    }
  ],
  "sObject": "Account",
  "where": {
    "left": {
      "field": "Id",
      "operator": "IN",
      "valueQuery": {
        "fields": [
          {
            "type": "Field",
            "field": "AccountId"
          }
        ],
        "sObject": "Opportunity"
      }
    }
  }
}
```
I think it should also return the literal type like this.
```
{
  ...
  "where": {
    "left": {
      ...
      "operator": "IN",
      "literalType": "SUBQUERY"
      "valueQuery": {
        ...
      }
    }
  }
}
```
This would help to handle the results afterward.
I'm not sure if there are any other `literalType` that is ommited from the final result, but if there are, please keep them as well

**Comment by paustint** [comment]
This does appear to be a bug, I will take a look into it.

I am on holiday now, so it may be a few days before I am able to investigate.
