### ISSUE TITLE
119 node module warnings in the console

### ISSUE THREAD

**Issue by justinleebehnke** [paustint/soql-parser-js#67]
- [ ] Feature
- [X] Bug Request

## Description
When I installed your library (which I love) I noticed that I have a ton of warnings in my browser of the following form:
```
/node_modules/antlr4ts/Token.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/Token.ts': Error: Can't resolve '../../src/Token.ts' in '/home/myuser/parentFolder/projectFolder/node_modules/antlr4ts'
```
My application is a React project using TypeScript and it may have something to do with webpack but I am not sure. This is not a high priority since it only appears in `npm run dev` but it is a little bit annoying. 
But your library much more than makes up for it so thank you so much for working so hard on this repo!

**Comment by paustint** [comment]
@justinleebehnke 
I am really glad this library is working out for you!

I think that it is probably something with your webpack config - the errors look like they are from antlr - which I don't have control over, but I am really surprised you are seeing these, as I have used this with React (look at example site for the code, it uses CRA: https://github.com/paustint/soql-parser-js/tree/master/docs).  In addition, I it has worked perfectly in an angular app as well.

Would you mind providing your webpack config info and your tsconfig files to see if I can build a small app that reproduces this?

**Comment by justinleebehnke** [comment]
The lead front end guy on my team did some digging and you are correct. He said he had to add `exclude` in the snippet below in the WebPack config and that got rid of the errors.
Now closing thank you so much!
```
    {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
          path.join(process.cwd(), 'node_modules')
        ]
      }
```
