### ISSUE TITLE
Function and Field in HAVING clause are ignored

### ISSUE THREAD

**Issue by ABenassi87** [paustint/soql-parser-js#7]
I tried to parse a SOQL Query got from Salesforce Examples:
SELECT LeadSource, COUNT(Name)
FROM Lead
GROUP BY LeadSource
HAVING COUNT(Name) > 100 and LeadSource > 'Phone'

The result was:
``` json
{
  "fields": [
    {
      "text": "LeadSource"
    },
    {
      "fn": {
        "text": "COUNT(Name)",
        "name": "COUNT",
        "parameter": "Name"
      }
    }
  ],
  "subqueries": [],
  "whereClauseGroups": [],
  "sObject": "Lead",
  "groupBy": {
    "field": "LeadSource"
  },
  "having": {
    "fn": {},
    "operator": ">",
    "value": "'Phone'"
  }
}
```

The function COUNT(Name) and the field LeadSource in HAVING Clause are ignored.

**Comment by paustint** [comment]
@ABenassi87 - it looks like the actual issue with this one is that we don't account for a scenario where there are multiple conditions in the HAVING clause so we overwrite the prior entry, this we only see "leadSource".  We are also missing the field name if HAVING is not a function
